[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTimeout = 1800

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1
startCommand = "/docker-entrypoint.sh"

[[deploy.env]]
PORT = "${{PORT}}"